### ISSUE TITLE
(Backend) Enable users to update escape rooms that have already been created

### ISSUE THREAD

**Issue by zackrylangford** [zackrylangford/escape-room-builder-backend#2]
Update the lambda function and API in order to allow users to make edits to their already created escape rooms.

**Comment by zackrylangford** [comment]
## Todo

- [x] Update the python lambda function to update the escape room data
- [x] deploy backend to prep for a test
- [x] run a lambda console test to make sure it is working
- [x] Test with the completed frontend
